# Generated by Django 4.2.9 on 2026-10-03 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='intake_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out_intakes', to=settings.AUTH_USER_MODEL, verbose_name='收件人'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='收件时间'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='release_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out_releases', to=settings.AUTH_USER_MODEL, verbose_name='放行人'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='放行时间'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out_operations', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('received', '已收件'), ('rejected', '已拒绝'), ('completed', '已放行')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
