# Generated by Django 4.2.9 on 2026-10-03 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personnelqualification_qualificationtype_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='qualification_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='personnel.qualificationcheck', verbose_name='审批资质核验记录'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='qualification_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ins', to='personnel.qualificationcheck', verbose_name='收件资质核验记录'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='last_block_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近阻断时间'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='last_block_reason',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='最近阻断原因'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='qualification_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_outs', to='personnel.qualificationcheck', verbose_name='放行资质核验记录'),
        ),
    ]
