# Generated by Django 4.2.9 on 2026-10-03 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0002_stockout_approved_at_stockout_approver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(blank=True, max_length=80, verbose_name='证件编号')),
                ('version', models.CharField(blank=True, max_length=30, verbose_name='证件版本')),
                ('valid_from', models.DateField(verbose_name='生效日期')),
                ('valid_until', models.DateField(verbose_name='有效期至')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期'), ('revoked', '已撤销')], default='active', max_length=20, verbose_name='状态')),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='撤销时间')),
                ('issued_by', models.CharField(blank=True, max_length=150, verbose_name='发证/授权机关')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL, verbose_name='持证人员')),
            ],
            options={
                'verbose_name': '人员资质',
                'verbose_name_plural': '人员资质',
                'db_table': 'qa_qualification',
                'ordering': ['-valid_until'],
            },
        ),
        migrations.CreateModel(
            name='QualificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='资质类型编码')),
                ('name', models.CharField(max_length=100, verbose_name='资质类型名称')),
                ('version', models.CharField(max_length=30, verbose_name='版本')),
                ('applicable_business', models.JSONField(default=list, help_text='该资质适用的业务节点，取值为 approval/receive/release', verbose_name='适用业务')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qualification_types', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '资质类型',
                'verbose_name_plural': '资质类型',
                'db_table': 'qa_qualification_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='QualificationWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(choices=[('approval', '审批'), ('receive', '收件'), ('release', '放行')], max_length=20, verbose_name='适用业务')),
                ('reason', models.TextField(verbose_name='豁免事由')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='批准时间')),
                ('valid_from', models.DateTimeField(verbose_name='豁免开始时间')),
                ('valid_until', models.DateTimeField(verbose_name='豁免截止时间')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='撤销时间')),
                ('revoke_reason', models.TextField(blank=True, verbose_name='撤销原因')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_waivers', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_waivers', to=settings.AUTH_USER_MODEL, verbose_name='被豁免人员')),
                ('qualification_type', models.ForeignKey(blank=True, help_text='为空表示豁免该业务要求的全部资质', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waivers', to='qualifications.qualificationtype', verbose_name='豁免的资质类型')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_waivers', to=settings.AUTH_USER_MODEL, verbose_name='撤销人')),
                ('stock_out', models.ForeignKey(blank=True, help_text='为空表示在时限内对该人员的同类业务普遍有效', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification_waivers', to='warehouse.stockout', verbose_name='关联出库单')),
            ],
            options={
                'verbose_name': '资质临时豁免',
                'verbose_name_plural': '资质临时豁免',
                'db_table': 'qa_qualification_waiver',
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='QualificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('renew', '续证'), ('revoke', '资质撤销'), ('waiver', '临时豁免'), ('waiver_revoke', '豁免撤销')], max_length=20, verbose_name='事件类型')),
                ('business', models.CharField(blank=True, choices=[('approval', '审批'), ('receive', '收件'), ('release', '放行')], max_length=20, verbose_name='涉及业务')),
                ('approval_basis', models.TextField(help_text='批准文件/决定编号、口头授权记录等据以批准的依据', verbose_name='批准依据')),
                ('approved_by', models.CharField(blank=True, max_length=100, verbose_name='批准人姓名/职务')),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('previous_valid_until', models.DateField(blank=True, null=True, verbose_name='原有效期至')),
                ('new_valid_until', models.DateField(blank=True, null=True, verbose_name='新有效期至')),
                ('detail', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='qualifications.qualification', verbose_name='相关资质')),
                ('waiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='qualifications.qualificationwaiver', verbose_name='相关豁免')),
            ],
            options={
                'verbose_name': '资质事件',
                'verbose_name_plural': '资质事件',
                'db_table': 'qa_qualification_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='qualifications.qualificationtype', verbose_name='资质类型'),
        ),
        migrations.CreateModel(
            name='QualificationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(choices=[('approval', '审批'), ('receive', '收件'), ('release', '放行')], max_length=20, verbose_name='业务节点')),
                ('result', models.CharField(choices=[('passed', '核验通过'), ('waived', '豁免通过'), ('blocked', '已阻断'), ('failed', '核验失败')], max_length=20, verbose_name='核验结果')),
                ('basis', models.CharField(blank=True, help_text='qualification=凭有效资质，waiver=凭临时豁免', max_length=20, verbose_name='通过依据')),
                ('evidence_snapshot', models.JSONField(default=dict, verbose_name='当时资质状态快照')),
                ('failure_reasons', models.JSONField(default=list, verbose_name='不满足原因')),
                ('need_reassign', models.BooleanField(default=False, verbose_name='需重新分配')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='核验时间')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_checks', to=settings.AUTH_USER_MODEL, verbose_name='被核验人')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='qualifications.qualification', verbose_name='据以通过的资质')),
                ('stock_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_checks', to='warehouse.stockout', verbose_name='出库记录')),
                ('waiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='qualifications.qualificationwaiver', verbose_name='据以通过的豁免')),
            ],
            options={
                'verbose_name': '资质核验记录',
                'verbose_name_plural': '资质核验记录',
                'db_table': 'qa_qualification_check',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['stock_out', 'business'], name='qa_qualific_stock_o_11ceab_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.UniqueConstraint(fields=('holder', 'qualification_type', 'certificate_no'), name='uniq_qualification_holder_type_cert'),
        ),
    ]
