# Generated by Django 4.2.9 on 2026-10-03 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(blank=True, max_length=80, verbose_name='证件编号')),
                ('version', models.CharField(max_length=30, verbose_name='发证版本')),
                ('valid_from', models.DateField(verbose_name='生效日期')),
                ('valid_until', models.DateField(verbose_name='有效期至')),
                ('status', models.CharField(choices=[('valid', '有效'), ('revoked', '已撤销')], default='valid', max_length=20, verbose_name='状态')),
                ('grant_basis', models.CharField(blank=True, max_length=200, verbose_name='取得/续证批准依据')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('revoke_reason', models.CharField(blank=True, max_length=200, verbose_name='撤销原因/依据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_qualifications', to=settings.AUTH_USER_MODEL, verbose_name='登记批准人')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='personnel.stockoutperson', verbose_name='持证人员')),
            ],
            options={
                'verbose_name': '人员资质',
                'verbose_name_plural': '人员资质',
                'db_table': 'pm_personnel_qualification',
                'ordering': ['-valid_until', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='资质类型')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类型编码')),
                ('version', models.CharField(max_length=30, verbose_name='版本')),
                ('applicable_business', models.JSONField(default=list, help_text='该资质可覆盖的业务节点编码，如 ["approval", "release"]', verbose_name='适用业务')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qualification_types', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '资质类型',
                'verbose_name_plural': '资质类型',
                'db_table': 'pm_qualification_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='QualificationExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(choices=[('receiving', '收件'), ('approval', '审批'), ('release', '放行')], max_length=20, verbose_name='适用业务')),
                ('reason', models.CharField(max_length=200, verbose_name='豁免事由')),
                ('basis', models.CharField(max_length=200, verbose_name='批准依据')),
                ('valid_from', models.DateField(verbose_name='生效日期')),
                ('valid_until', models.DateField(verbose_name='有效期至')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='是否已撤销')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('revoke_reason', models.CharField(blank=True, max_length=200, verbose_name='撤销原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exemptions', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='personnel.stockoutperson', verbose_name='被豁免人员')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_exemptions', to=settings.AUTH_USER_MODEL, verbose_name='豁免撤销人')),
            ],
            options={
                'verbose_name': '临时豁免',
                'verbose_name_plural': '临时豁免',
                'db_table': 'pm_qualification_exemption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualificationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(choices=[('receiving', '收件'), ('approval', '审批'), ('release', '放行')], max_length=20, verbose_name='业务节点')),
                ('result', models.CharField(choices=[('pass', '核验通过'), ('blocked', '已阻断')], max_length=20, verbose_name='核验结果')),
                ('grant_type', models.CharField(blank=True, choices=[('qualification', '有效资质'), ('exemption', '临时豁免')], max_length=20, verbose_name='放行依据类型')),
                ('snapshot', models.JSONField(default=dict, verbose_name='当时资质状态快照')),
                ('detail', models.CharField(blank=True, max_length=300, verbose_name='核验说明')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='核验时间')),
                ('exemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='personnel.qualificationexemption', verbose_name='核验依据豁免')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_checks', to='personnel.stockoutperson', verbose_name='值班人员')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='personnel.personnelqualification', verbose_name='核验依据资质')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_checks', to=settings.AUTH_USER_MODEL, verbose_name='操作账号')),
            ],
            options={
                'verbose_name': '资质核验记录',
                'verbose_name_plural': '资质核验记录',
                'db_table': 'pm_qualification_check',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='QualificationChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('grant', '登记发证'), ('renew', '续证'), ('revoke', '撤销资质'), ('exempt', '批准豁免'), ('exempt_revoke', '撤销豁免')], max_length=20, verbose_name='变更类型')),
                ('business', models.CharField(blank=True, choices=[('receiving', '收件'), ('approval', '审批'), ('release', '放行')], max_length=20, verbose_name='涉及业务')),
                ('basis', models.CharField(max_length=200, verbose_name='批准依据')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_approvals', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('exemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='personnel.qualificationexemption', verbose_name='相关豁免')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_logs', to='personnel.stockoutperson', verbose_name='人员')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='personnel.personnelqualification', verbose_name='相关资质')),
            ],
            options={
                'verbose_name': '资质变更记录',
                'verbose_name_plural': '资质变更记录',
                'db_table': 'pm_qualification_change_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='personnelqualification',
            name='qualification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='personnel.qualificationtype', verbose_name='资质类型'),
        ),
        migrations.AddField(
            model_name='personnelqualification',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_qualifications', to=settings.AUTH_USER_MODEL, verbose_name='撤销批准人'),
        ),
    ]
